-d C:\Users\palko\Desktop\NVG\Uj_kezdes\Uj_kezdes4.3.3 BOB linebuff\impl\gwsynthesis\Uj_kezdes1.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Users\palko\Desktop\NVG\Uj_kezdes\Uj_kezdes4.3.3 BOB linebuff\src\Uj_kezdes1.cst
-cfg C:\Users\palko\Desktop\NVG\Uj_kezdes\Uj_kezdes4.3.3 BOB linebuff\impl\pnr\device.cfg
-sdc C:\Users\palko\Desktop\NVG\Uj_kezdes\Uj_kezdes4.3.3 BOB linebuff\src\Uj_kezdes1.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
